### ISSUE TITLE
Relevant Packages

### ISSUE THREAD

**Issue by bransonf** [knapply/networksf#1]
You're probably aware of `shp2graph` and it's integration to `igraph`. This is what I've used before, specifically for calculating shortest path along road networks.

That said, I'm hoping the aim of this package is to modernize those implementations. `shp2graph` still uses `sp` classes rather than the `sf` class.

And I don't know your goals necessarily, but might I suggest a feature to correct topology in road data. OSM is notoriously bad as far as usable network data is concerned, as is TIGER line geometry.

Something similar was implemented in the python package `osmnx` See [this file](https://github.com/gboeing/osmnx/blob/master/osmnx/simplify.py)

Thanks for the consideration, and very excited to follow the development of this package.

**Comment by knapply** [comment]
Thanks for the info! To clarify, the focus here (when I can get to it) won't be transportation networks. That said, I'll probably take a look at the packages you referenced to see what may be relevant.

If you haven't looked at it, [`{dodgr}`](https://atfutures.github.io/dodgr/) may be more what you're looking for.

**Comment by bransonf** [comment]
Thanks @knapply for showing me `dodgr`, that's extremely helpful. Best of luck with the development of this package, always excited to see novel spatial methods developed.
